@extends('admin.layouts.app') @section('title',$product->exists?'Edit Product':'Add Product') @section('content')
<div class="tf-section-2"><h4>{{$product->exists?'Edit Product':'Add Product'}}</h4></div>
<div class="wg-box mt-3"><form method="POST" enctype="multipart/form-data" action="{{$product->exists?route('admin.products.update',$product):route('admin.products.store')}}">@csrf @if($product->exists)@method('PUT')@endif
<div class="row g-3"><div class="col-md-6"><label>Product Name</label><input class="form-control" name="name" value="{{old('name',$product->name)}}" required></div><div class="col-md-6"><label>Slug</label><input class="form-control" name="slug" value="{{old('slug',$product->slug)}}"></div>
<div class="col-md-6"><label>Category</label><select class="form-select" name="category_id" required>@foreach($categories as $c)<option value="{{$c->category_id}}" @selected(old('category_id',$product->category_id)==$c->category_id)>{{$c->name}}</option>@endforeach</select></div>
<div class="col-md-6"><label>Brand</label><select class="form-select" name="brand_id"><option value="">No brand</option>@foreach($brands as $b)<option value="{{$b->brand_id}}" @selected(old('brand_id',$product->brand_id)==$b->brand_id)>{{$b->name}}</option>@endforeach</select></div>
<div class="col-12"><label>Description</label><textarea class="form-control" rows="5" name="description">{{old('description',$product->description)}}</textarea></div>
<div class="col-md-3"><label>SKU Code</label><input class="form-control" name="sku_code" value="{{old('sku_code',$sku?->sku_code)}}" required></div>
<div class="col-md-3"><label>Price</label><input class="form-control" type="number" step="0.01" min="0" name="price" value="{{old('price',$sku?->price)}}" required></div>
<div class="col-md-3"><label>Stock</label><input class="form-control" type="number" min="0" name="stock_quantity" value="{{old('stock_quantity',$sku?->stock_quantity ?? 0)}}" required></div>
<div class="col-md-3"><label>Image</label><input class="form-control" type="file" name="image" accept="image/*">@if($sku?->image_url)<small>Current image: {{$sku->image_url}}</small>@endif</div>
<div class="col-12"><label>Attribute Values</label><div class="row">@foreach($attributeValues->groupBy(fn($v)=>$v->attribute->name) as $attribute=>$vals)<div class="col-md-4"><div class="border rounded p-3 mb-2"><strong>{{$attribute}}</strong>@foreach($vals as $v)<div class="form-check"><input class="form-check-input" type="checkbox" name="attribute_values[]" value="{{$v->value_id}}" @checked($sku?->attributeValues?->contains('value_id',$v->value_id))><label class="form-check-label">{{$v->value}}</label></div>@endforeach</div></div>@endforeach</div></div>
<div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active',$product->exists?$product->is_active:true))><label class="form-check-label">Active</label></div></div></div>
<button class="tf-button style-1 mt-4">Save Product</button></form></div>@endsection
