@extends('admin.layouts.master')
@section('title','Dashboard')
@section('content')
<div class="main-content-wrap"><div class="flex items-center flex-wrap justify-between gap20 mb-27"><h3>Dashboard</h3><ul class="breadcrumbs flex items-center flex-wrap justify-start gap10"><li><div class="text-tiny">Home</div></li><li><i class="icon-chevron-right"></i></li><li><div class="text-tiny">Dashboard</div></li></ul></div>
<div class="tf-section-4 mb-30"><div class="wg-chart-default"><div class="flex items-center justify-between"><div class="flex items-center gap14"><div class="image type-white"><i class="icon-shopping-cart"></i></div><div><div class="body-text mb-2">Total Products</div><h4>{{ number_format($productCount) }}</h4></div></div></div></div><div class="wg-chart-default"><div class="flex items-center justify-between"><div class="flex items-center gap14"><div class="image type-white"><i class="icon-layers"></i></div><div><div class="body-text mb-2">Categories</div><h4>{{ number_format($categoryCount) }}</h4></div></div></div></div><div class="wg-chart-default"><div class="flex items-center justify-between"><div class="flex items-center gap14"><div class="image type-white"><i class="icon-file"></i></div><div><div class="body-text mb-2">Orders</div><h4>{{ number_format($orderCount) }}</h4></div></div></div></div><div class="wg-chart-default"><div class="flex items-center justify-between"><div class="flex items-center gap14"><div class="image type-white"><i class="icon-users"></i></div><div><div class="body-text mb-2">Customers</div><h4>{{ number_format($customerCount) }}</h4></div></div></div></div></div>
<div class="tf-section-5"><div class="wg-box"><div class="flex items-center justify-between mb-20"><h5>Recent Orders</h5><a class="view-all" href="{{ route('orders.index') }}">View all <i class="icon-chevron-right"></i></a></div><div class="wg-table"><ul class="table-title flex gap20 mb-14"><li><div class="body-title">Order</div></li><li><div class="body-title">Customer</div></li><li><div class="body-title">Total</div></li><li><div class="body-title">Status</div></li></ul>@forelse($recentOrders as $order)<ul class="flex items-center gap20 mb-14"><li class="flex-grow"><a class="body-title-2" href="{{ route('orders.show',$order) }}">{{ $order->order_number }}</a></li><li class="flex-grow"><div class="body-text">{{ $order->user->name ?? $order->shipping_name }}</div></li><li class="flex-grow"><div class="body-text">৳{{ number_format($order->total,2) }}</div></li><li><span class="block-available">{{ ucfirst($order->status) }}</span></li></ul>@empty<div class="body-text">No orders yet.</div>@endforelse</div></div><div class="wg-box"><div class="flex items-center justify-between mb-20"><h5>Low Stock Products</h5><a class="view-all" href="{{ route('products.index') }}">View all</a></div><div class="wg-table table-top-product">@forelse($lowStockProducts as $product)<div class="product-item gap14 mb-14"><div class="image"><img src="{{ $product->image ? asset('storage/'.$product->image) : asset('assets/images/products/1.png') }}" alt=""></div><div class="flex items-center justify-between flex-grow"><div><div class="body-title-2">{{ $product->name }}</div><div class="text-tiny mt-3">SKU: {{ $product->sku }}</div></div><div class="body-title-2">{{ $product->stock }} left</div></div></div>@empty<div class="body-text">No low stock products.</div>@endforelse</div></div></div>
<div class="tf-section-5 mt-30"><div class="wg-box"><h5>Sales Overview</h5><div class="mt-20"><h2>৳{{ number_format($salesTotal,2) }}</h2><div class="body-text">Completed/active order sales</div></div></div><div class="wg-box"><h5>Quick Actions</h5><div class="flex gap10 mt-20 flex-wrap"><a class="tf-button" href="{{ route('products.create') }}">Add Product</a><a class="tf-button style-2" href="{{ route('categories.create') }}">Add Category</a><a class="tf-button style-2" href="{{ route('orders.create') }}">Create Order</a></div></div></div>
</div>
@endsection
